# Generated by Django 2.2.6 on 2022-03-07 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='dateNextReviewed',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
