# Generated by Django 2.2.6 on 2022-03-07 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_card_datenextreviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='dateNextReviewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
