# Generated by Django 2.2.6 on 2022-03-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220307_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='numberOfTimesWrong',
            field=models.IntegerField(default=0),
        ),
    ]
